# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc3f6e6789046b170166564f9c430e48ead7ad7a5bbd43386db25a6bd16df6cac1e0e105bc3645b2a423d7d9babdbd8e8652291682b2ce4cfea1d4b1d6d78ee6

test:
  secret_key_base: 6e87629a7cd954bb9b68fc7d7ff5ac49a8d6200c679f60307758a6c3b09e496fc874637fe1627b4ba3833c6ce3812fc86a7b877f868cc59e63d96a067ca18b94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
